add
Sergii112/AQA-playwright pull request #4
Opened 2024-04-08 11:48 UTC by Sergii112

2024-04-08 19:51 UTC, sttaran requested changes

2024-04-08 19:51 UTC, sttaran commented on tests/regForm_DZ18.spec.js
> +            await page.goto("https://qauto.forstudy.space/");
you baseUrl in you playwright config, use relative path

2024-04-08 19:51 UTC, sttaran commented on tests/regForm_DZ18.spec.js
> +            await expect(nameInput).not.toHaveClass("invalid");
use https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-css

2024-04-08 19:51 UTC, sttaran commented on tests/regForm_DZ18.spec.js
> +            await expect(nameInput).not.toHaveClass("invalid");
you should check border color in every negative scenario

2024-04-08 19:51 UTC, sttaran commented on tests/regForm_DZ18.spec.js
> +            await lastNameInput.focus()
these 2 rows probably are redundant in every test

2024-04-08 19:51 UTC, sttaran commented on tests/regForm_DZ18.spec.js
> +           const errorMessage = page.locator('.invalid-feedback');
`const errorMessage = passwordInput.locator(' + .invalid-feedback');`

2024-04-20 14:03 UTC, Sergii112 reviewed
done

2024-04-20 14:03 UTC, merged